CC = g++
CFLAGS = -std=c++11
LFLAGS = -Wall
OBJS = 
TARGET =

ch3.0_josephus.out: ch3.0_josephus.cpp
	$(CC) $(CFLAGS) ch3.0_josephus.cpp -o ch3.0_josephus.out

ch3.0_2-3_test.out: ch3.0_2.cpp ch3.0_3.cpp ch3.0_2-3_test.cpp
	$(CC) $(CFLAGS) ch3.0_2-3_test.cpp -o ch3.0_2-3_test.out

clean:
	rm *.out
